src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse_num;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_libelle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse_complement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="commandes")
     */
    private $utilisateur;

    /**
     * @ORM\ManyToMany(targetEntity=Produit::class, mappedBy="commandes")
     */
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getAdresseNum(): ?string
    {
        return $this->adresse_num;
    }

    public function setAdresseNum(string $adresse_num): self
    {
        $this->adresse_num = $adresse_num;

        return $this;
    }

    public function getAdresseLibelle(): ?string
    {
        return $this->adresse_libelle;
    }

    public function setAdresseLibelle(string $adresse_libelle): self
    {
        $this->adresse_libelle = $adresse_libelle;

        return $this;
    }

    public function getAdresseComplement(): ?string
    {
        return $this->adresse_complement;
    }

    public function setAdresseComplement(string $adresse_complement): self
    {
        $this->adresse_complement = $adresse_complement;

        return $this;
    }

    public function getAdresseCp(): ?string
    {
        return $this->adresse_cp;
    }

    public function setAdresseCp(string $adresse_cp): self
    {
        $this->adresse_cp = $adresse_cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->addCommande($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeCommande($this);
        }

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Commande;
use App\Entity\Utilisateur;


class AccueilController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function index(): Response
    {
        $user = $this->getUser();
        $collections = $this->getDoctrine()->getRepository(Categorie::class)->findAll();
        return $this->render('accueil/index.html.twig', [
            'controller_name' => 'AccueilController',
            'user' => $user,
            'collections' =>$collections,
        ]);
    }
    /**
     * @Route("/client", name="client")
     */
    public function client(): response
    {
        $user = $this->getUser();
        //$client = $this->getDoctrine()->getRepository(Utilisateur::class)->find($user);
        $commandes = $user->getCommandes();
        return $this->render('accueil/client.html.twig', 
    [
        'user' =>$user,
        'commandes' => $commandes,
    ]);
    }

    /**
     * @Route("/engagement", name="engagement")
     */
    public function engagement(): Response
    {
        $user = $this->getUser();
        
        return $this->render('accueil/engagement.html.twig', [
            'controller_name' => 'AccueilController',
            'user' => $user,
            
        ]);
    }

    /**
     * @Route("/livraisons", name="livraisons")
     */
    public function livraisons(): Response
    {
        $user = $this->getUser();
        
        return $this->render('accueil/livraisons.html.twig', [
            'controller_name' => 'AccueilController',
            'user' => $user,
            
        ]);
    }

    /**
     * @Route("/confidentialite", name="confidentialite")
     */
    public function confidentialite(): Response
    {
        $user = $this->getUser();
        
        return $this->render('accueil/confidentialite.html.twig', [
            'controller_name' => 'AccueilController',
            'user' => $user,
            
        ]);
    }

    /**
     * @Route("/conditions", name="conditions")
     */
    public function conditions(): Response
    {
        $user = $this->getUser();
        
        return $this->render('accueil/conditions.html.twig', [
            'controller_name' => 'AccueilController',
            'user' => $user,
            
        ]);
    }

    /**
     * @Route("/mentionsLgl", name="mentionsLgl")
     */
    public function mentionsLgl(): Response
    {
        $user = $this->getUser();
        
        return $this->render('accueil/mentionsLgl.html.twig', [
            'controller_name' => 'AccueilController',
            'user' => $user,
            
        ]);
    }

    /**
     * @Route("/qr", name="qr")
     */
    public function qr(): Response
    {
        $user = $this->getUser();
        
        return $this->render('accueil/qr.html.twig', [
            'controller_name' => 'AccueilController',
            'user' => $user,
            
        ]);
    }
}

templates/accueil/client.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<h1 class="center-align"> Hello {{app.user.email}}</h1>
  <div class="row">
    <div class="col s12">
      <ul class="tabs" id="tabs">
        <li class="tab col s6"><a class="active" href="#test1">Informations client</a></li>
        <li class="tab col s6"><a href="#test2">Historique des commandes</a></li>
       
      </ul>
    </div>
    <div id="test1" class="col s12">
    <br>
    <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <input disabled value= "{{app.user.email}}" id="email" type="text" class="validate">
          <label for="first_name">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input disabled value="{{app.user.AdresseLibelle}}" id="Adresse" type="text" class="validate">
          <label for="Adresse">Adresse</label>
        </div>
      </div>
       <div class="row">
        <div class="input-field col s12">
          <input disabled value="{{app.user.AdresseCp}}" id="cp" type="text" class="validate">
          <label for="cp">Code postal</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input disabled value="{{app.user.Ville}}" id="ville" type="text" class="validate">
          <label for="ville">Ville</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input disabled value="{{app.user.Pays}}" id="pays" type="text" class="validate">
          <label for="pays">Ville</label>
        </div>
      </div>
      </div>
      <div class="row">
        <a class="waves-effect waves-light btn">Modifier</a>
      </div>
      </div>
    </form>
  </div>
    
    
    
    
    </div>
    <div id="test2" class="col s12">
          <table class="striped">
        <thead>
          <tr>
              <th>Date : </th>
              <th>Total :</th>
              <th>Statut : </th>
              <th>Adresse expédiée : </th>
              <th>Code postal : </th>
              <th>Ville :</th>
              <th>Pays : </th>
              <th>Facture : </th>
          </tr>
        </thead>

        <tbody>
        {% for obj in commandes %}
          <tr>
            
            <td>{{obj.date|date('Y-m-d')}}</td>
            <td>{{obj.montant}}</td>
            <td>{{obj.statut}}</td>
            <td>{{obj.adresseLibelle}}</td>
            <td>{{obj.adresseCp}}</td>
            <td>{{obj.Ville}}</td>
            <td>{{obj.Pays}}</td>
            <td><a class="waves-effect waves-light btn">Facture</a>
</td>
          </tr>
           {% endfor %}
        </tbody>
      </table>
    
    
    
    
    
    </div>

  </div>
{% endblock %}

templates/accueil/conditions.html.twig
  {% extends 'base.html.twig' %}

  {% block title %}Contact Form{% endblock %}

  {% block body %}
  <div class="row">
      <div class="container">
          <h5>
              <center>Conditions générales de vente</center>
          </h5>
          <div class="row col s12">
              <div>
                  <p>
                      <center>DÉCLARATION DE CONFIDENTIALITÉ</center>
                  </p>
                  <p>
                      <center>Conditions Générales de Vente de LA COQUERIE™
                          En poursuivant votre navigation sur ce site, vous acceptez l'utilisation de cookies pour vous
                          proposer des offres adaptées à vos centres d'intérêt, recueillir des données de statistiques
                          et permettre le partage de pages sur les réseaux sociaux.</center>
                  </p>
                  <p>
                      <center>Merci de votre intérêt pour nos produits ! Vous trouverez ci-dessous les Conditions
                          Générales de Vente s’appliquant à votre achat, qui visent à expliciter vos droits. Si vous
                          avez des questions, n’hésitez pas à nous contacter, nous nous ferons un plaisir de vous
                          expliquer leur fonctionnement.
                      </center>
                  </p>

              </div>
          </div>
      </div>
  </div>
  {% endblock %}

templates/accueil/confidentialite.html.twig
  {% extends 'base.html.twig' %}

  {% block title %}Contact Form{% endblock %}

  {% block body %}
  <div class="row">
      <div class="container">
          <h5>
              <center>Politique de confidentialité</center>
          </h5>
          <div class="row col s12">
              <div>
                  <p>
                      <center>DÉCLARATION DE CONFIDENTIALITÉ</center>
                  </p>
                  <center>----</center><br>
                  <p>
                      <center>ARTICLE 1 – RENSEIGNEMENTS PERSONNELS RECUEILLIS</center>
                  </p>
                  <p>
                      <center>Lorsque vous effectuez un achat sur notre boutique, dans le cadre de notre processus
                          d’achat et de vente, nous recueillons les renseignements personnels<br> que vous nous
                          fournissez,
                          tels que votre nom, votre adresse et<br> votre adresse e-mail.</center>
                  </p>
                  <p>
                      <center>ARTICLE 2</center>
                  </p>
                  <p>
                      <center>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas scelerisque tristique
                          tempus. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia
                          nostra, per inceptos himenaeos. Sed vel vulputate lacus. Sed interdum, velit vitae dictum
                          feugiat, mi sem placerat dui, et blandit sapien diam in eros. Mauris suscipit, massa et
                          porttitor maximus, magna felis mattis arcu, non posuere diam purus ut sapien. Pellentesque at
                          porttitor diam. Vivamus vulputate luctus luctus. Integer scelerisque finibus massa in pretium.
                          Fusce convallis ipsum purus, in cursus nibh laoreet ac. Duis ut commodo libero. Etiam dapibus
                          lorem eget libero lacinia, efficitur bibendum nibh auctor. Nulla in sodales metus, sit amet
                          gravida elit. Aenean bibendum venenatis elit, rhoncus cursus est pretium ac. Curabitur
                          fringilla sollicitudin ornare. Suspendisse sit amet sapien vel orci consectetur dignissim.
                      </center>
                  </p>

              </div>
          </div>
      </div>
  </div>
  {% endblock %}

templates/accueil/engagement.html.twig
  {% extends 'base.html.twig' %}

  {% block title %}Contact Form{% endblock %}

  {% block body %}
  <div class="row">
      <div class="container">
          <h5>
              <center>L'ÉCOQUERIE&nbsp;&nbsp;<i class="fas fa-leaf"></i></center>
          </h5>
          <div class="row">
              <div>
                  <center>
                      <img class="logo_payment"
                          src="https://cdn.shopify.com/s/files/1/0032/9223/3837/files/nos_engagements_-_l_ecoquerie.jpg?v=1603976801">
                  </center>
              </div>
          </div>
          <div class="row">
              <div>
                  <p>Parce que la bonne santé de notre planète nous concerne tous, La Coquerie™ s'adapte.<br>
                      Nous garantissons l'envoi de 90% de commandes sans emballage plastique. Alors que la majeur partie
                      des marques de coques de téléphone emballent leurs produits dans des sachets plastiques inutiles,
                      nous avons décidé de tout faire pour réduire leur utilisation au maximum.<br>
                      Cette mesure touche également nos enveloppes, qui en majeur partie se font sans plastique bulle
                      tout en vous assurant la bonne protection de vos produits.</p>
                  <p>Afin de réduire le stock inutile, et par conséquent le transport inutile et nos déchets, nos coques
                      sont fabriquées à la commande et selon votre modèle de smartphone.<br>
                      Aucune de nos coques n'est pré-fabriquée ni pré-imprimée avant que votre commande ne soit validée.<br>
                      De par le fait et comme vous le comprendrez j'en suis sûr, nous n'acceptons pas les retours sauf
                      en cas d'erreur commise par notre équipe.<br>
                      C'est pour cette exacte raison que nous vous demanderons de bien vouloir vérifier votre commande
                      et notamment votre modèle de smartphone. Également, vous pouvez nous contacter depuis le bouton
                      tchat en bas à droite de notre site, où notre conseiller clientèle se fera un plaisir de vous
                      aider dans l'identification de votre smartphone.</p>
              </div>
          </div>
      </div>
  </div>
  {% endblock %}

templates/accueil/livraisons.html.twig
  {% extends 'base.html.twig' %}

  {% block title %}Contact Form{% endblock %}

  {% block body %}
  <div class="row">
      <div class="container">
          <h5>
              <center>LIVRAISONS</center>
          </h5>
          <div class="row">
              <div>
                  <p>Les frais de port sont offerts en ce moment sur notre site à partir de 29.99€ d'achat. La livraison
                      est assurée par lettre suivie et vos colis est déposé directement dans votre boîte aux lettres,
                      pas besoin d'être présent !</p>
                  <p>Toutes les commandes sont fabriquées, préparées et expédiées depuis notre atelier en France sous
                      24/48h ouvrés. Une fois votre commande envoyée par notre équipe, vous recevrez via mail/SMS un
                      lien vous permettant de suivre l'acheminement de votre colis.</p>
                  <p>Votre colis arrive sous 1 à 5 jours ouvrés en moyenne, après envoi. La livraison prend jusqu'à 10
                      jours ouvrés pour l'étranger.

                  </p>
              </div>
          </div>
      </div>
  </div>
  {% endblock %}

templates/accueil/mentionsLgl.html.twig
  {% extends 'base.html.twig' %}

  {% block title %}Contact Form{% endblock %}

  {% block body %}
  <div class="row">
      <div class="container">
          <h5>
              <center>MENTIONS LÉGALES</center>
          </h5>
          <div class="row col s12">
              <div>
                  <p>
                      Les contenus (textes, visuels, photos, données techniques, etc.) publiés sur le site
                          internet de la société LA COQUERIE ne peuvent être utilisés sans son consentement préalable ou
                          de l’un de ses représentants légaux. Ces contenus sont protégés au titre des droits d’auteur.
                          Toute distribution, modification ou reproduction de tout ou partie de ces contenus est
                          interdite sans l’accord écrit de la société LA COQUERIE. LA COQUERIE décline toute
                          responsabilité quant aux contenus des sites de ses partenaires ou de ses clients auxquels le
                          visiteur accéderait à partir de ce site.
                  </p>
                  <p>
                      Le site est édité par Nuytten Charles -LA COQUERIE, rue de l'Europe – France, immatriculée
                          au registre du commerce et des sociétés de Lille Métropole sous le numéro 844 682 146.
                      
                  </p>
                  <p>
                      L’hébergement du site est assuré par la société Shopify Inc dont le siège social est situé
                          126 York St. Ottawa, ON K1N 5T5, au Canada.
                      
                  </p>
                  <p>
                      Le directeur de la publication du site est Monsieur Nuytten Charles.
                      
                  </p>
              </div>
          </div>
      </div>
  </div>
  {% endblock %}

templates/accueil/qr.html.twig
  {% extends 'base.html.twig' %}

  {% block title %}Contact Form{% endblock %}

  {% block body %}
  <div class="row">
      <div class="container">
          <table class="striped">
              <thead>
                  <tr>
                      <th></th>
                      <th>
                          <h5>LIVRAISON</h5>
                      </th>
                  </tr>
              </thead>

              <tbody>
                  <tr>
                      <td><b>Combien coûte la livraison ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>La livraison est offerte sur l'ensemble de notre site, en ce moment !</td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>Ai-je besoin d'être présent(e) afin de réceptionner mon colis ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Non, inutile ! Votre facteur est chargé de vous transmettre votre colis dans votre boîte aux
                          lettres directement.
                          Si vous choisissez comme mode de livraison Colissimo ou Chronopost, il est préférable d'être
                          présent.</td>
                  </tr>
                  <tr>
                      <td><b>Quel est le délais de livraison ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Dès que votre commande est expédiée, comptez 1 à 5 jours de livraison pour la France. Pour
                          l'étranger, le délais peut aller jusqu'à 10 jours selon votre pays.</td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>Je n'ai reçu qu'une partie de ma commande..</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Pas de panique ! Nous avons 2 ateliers de fabrication et préparation de vos commandes. Il est
                          parfois nécessaire de procéder à deux envois différents, sans frais supplémentaire. :)</td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>Comment suivre ma commande ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Une fois votre commande expédiée, nous vous envoyons par mail ou SMS selon ce que vous avez
                          choisi, un lien afin de suivre votre commande.</td>
                      <td></td>
                  </tr>
              </tbody>
          </table>
          <table class="striped">
              <thead>
                  <tr>
                      <th></th>
                      <th>
                          <h5>PRODUITS</h5>
                      </th>
                  </tr>
              </thead>

              <tbody>
                  <tr>
                      <td><b>En quelle matière vos coques sont elles fabriquées ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Nos coques sont fabriquées en silicone ! Elles sont imprimées en ULTRA HD. Nous sommes les
                          seuls à bénéficier d'une tel qualité d'impression pour des produits Made in France.</td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>Où sont fabriquées vos produits ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>La majorité de nos produits sont fabriqués en France ! C'est notamment le cas pour nos coques,
                          et grips. Nous les fabriquons dans dans 2 ateliers différents, en France.</td>
                  </tr>
                  <tr>
                      <td><b>Vos produits sont-ils garantis ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Oui, nos coques et grips sont garantis 1 an, à partir de votre date d'achat. </td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>Comment-laisser mon avis sur le produit reçu ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Suite à votre commande, vous recevrez un mail vous proposant de laisser votre avis. Sinon,
                          vous pouvez le faire en vous rendant sur la page du produit que vous avez acheté, et laisser
                          votre avis juste en bas.</td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>Peut-on ajouter des emojis/smileys sur des produits personnalisés ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Oui bien sûr ! Attention : ils seront adaptés en fonction de notre système. Ils peuvent donc
                          être légèrement différents de ceux demandés.</td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>De quelle couleur sera le contours de ma coque ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Nous produisons l'essentiel de nos coques en couleur de contours "transparente", si cette
                          couleur n'est pas disponible sur votre modèle de téléphone, vous recevrez votre coque en
                          contours noirs.</td>
                      <td></td>
                  </tr>
              </tbody>
          </table>
          <table class="striped">
              <thead>
                  <tr>
                      <th></th>
                      <th>
                          <h5>AUTRES</h5>
                      </th>
                  </tr>
              </thead>

              <tbody>
                  <tr>
                      <td><b>Où se situe votre société LA COQUERIE™</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Notre société se situe en France, à Lille !</td>
                      <td></td>
                  </tr>
                  <tr>
                      <td><b>Peut-on trouver vos produits en magasin ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>L'ensemble des produits LA COQUERIE™ sont exclusifs à internet, pour le moment.</td>
                  </tr>
                  <tr>
                      <td><b>J'aimerai devenir ambassadeur/ambassadrice de votre marque, comment-faire ?</b></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td>Ce serait avec grand plaisir ! Pour cela c'est très simple, il vous suffit de nous écrire à
                          hello@la-coquerie.fr. Pensez à nous envoyer un lien de vos différents réseaux sociaux :)</td>
                      <td></td>
                  </tr>
              </tbody>
          </table>
      </div>
  </div>
  {% endblock %}